-- Texas Home Hub Pro V2 Property Management
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  address text,
  city text not null,
  state text not null default 'TX',
  zip text not null,
  county text,
  price numeric(12,2) not null check (price >= 0),
  beds numeric(4,1) not null default 0,
  baths numeric(4,1) not null default 0,
  sqft integer not null default 0,
  lot_sqft integer,
  year_built integer,
  property_type text not null default 'Single Family',
  category text not null default 'Residential' check (category in ('Residential','Commercial','Land','Multi-family','Luxury')),
  status text not null default 'draft' check (status in ('draft','active','pending','sold','archived')),
  badge text check (badge is null or badge in ('Featured','New','Open House','Pending','Sold')),
  description text,
  features text[] not null default '{}',
  featured boolean not null default false,
  published boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists properties_public_idx on public.properties(published,status,featured);
create index if not exists properties_location_idx on public.properties(city,zip);
create index if not exists property_images_property_idx on public.property_images(property_id,sort_order);

alter table public.properties enable row level security;
alter table public.property_images enable row level security;

create policy "Public reads published properties" on public.properties
for select using (published = true and status <> 'archived' or public.is_admin());
create policy "Admins insert properties" on public.properties for insert with check (public.is_admin());
create policy "Admins update properties" on public.properties for update using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete properties" on public.properties for delete using (public.is_admin());

create policy "Public reads images for published properties" on public.property_images
for select using (exists(select 1 from public.properties p where p.id = property_id and (p.published = true or public.is_admin())));
create policy "Admins insert property images" on public.property_images for insert with check (public.is_admin());
create policy "Admins update property images" on public.property_images for update using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete property images" on public.property_images for delete using (public.is_admin());

insert into storage.buckets (id,name,public)
values ('property-images','property-images',true)
on conflict (id) do update set public = excluded.public;

create policy "Public reads property image objects" on storage.objects for select using (bucket_id = 'property-images');
create policy "Admins upload property image objects" on storage.objects for insert with check (bucket_id = 'property-images' and public.is_admin());
create policy "Admins update property image objects" on storage.objects for update using (bucket_id = 'property-images' and public.is_admin());
create policy "Admins delete property image objects" on storage.objects for delete using (bucket_id = 'property-images' and public.is_admin());
